Repository rustprooflabs/pgosm-flex, pull requests merged in 2022-11, with the labels that each got.

#264 Fix using `--append` with input file
  docker/pgosm_flex.py
Labels: bug

#267 Minor cleanup to formatting and log messages
  docker/geofabrik.py
  docker/helpers.py
  docker/osm2pgsql_recommendation.py
  docker/pgosm_flex.py
Labels: Technical Debt

#269 Adjust Dockerfile to use PostGIS 3.3 instead of master branch that uses 3.4-dev
  Dockerfile
Labels: Technical Debt, Docker

#271 Add Make step to test initial --append call with --input-file
  Makefile
Labels: enhancement

#272 Always create osm schema and PostGIS extension
  docker/db.py
Labels: Technical Debt

#273 Improve logging
  docker/helpers.py
  docker/pgosm_flex.py
Labels: Technical Debt

#274 General updates, improvements and consistency throughout doc pages
  README.md
  docs/APPEND-MODE.md
  docs/DOCKER-BUILD.md
  docs/DOCKER-RUN.md
  docs/DUMP-AND-LOAD.md
  docs/LAYERSETS.md
  docs/MANUAL-STEPS-RUN.md
  docs/PERFORMANCE.md
  docs/PROJECTS.md
  docs/QUERY.md
Labels: documentation
