Repository rustprooflabs/pgosm-flex, pull requests merged in 2022-01, with the labels that each got.

#219 Be specific about osm2pgsql version
  Dockerfile
Labels: external, Docker

#220 Add troubleshooting section to manual steps readme
  docs/MANUAL-STEPS-RUN.md
Labels: documentation

#221 include aeroway tag
  flex-config/style/infrastructure.lua
Labels: bug

#223 Fix aeroway
  flex-config/style/infrastructure.lua
  tests/expected/infrastructure_line_osm_type_subtype_count.out
  tests/expected/infrastructure_point_osm_type_subtype_count.out
  tests/expected/infrastructure_polygon_osm_type_subtype_count.out
Labels: bug

#222 Support append mode
  README.md
  docs/APPEND-MODE.md
  docs/MANUAL-STEPS-RUN.md
  flex-config/sql/pgosm-meta.sql
  flex-config/sql/place.sql
  requirements.txt
Labels: enhancement
